# Intro numpy

#### numpy is a liabrary its used for creatin for array.
#### we use array as one diamensional, multi-diamensional.
#### array is collection of similar type of data.

In [5]:
import numpy as np

In [5]:
an_array = np.array([3,33,333]) # create a rank 1 array, create 1 row

print(type(an_array)) # The type of an ndarray is : "<class:numpy.ndarray>"

<class 'numpy.ndarray'>


In [6]:
#test the shape of the array we just created, it should have just one dimension
print(an_array.shape) # beacuse 1 rank only 3 print

(3,)


In [8]:
#print this is a 1-rank array, we need only one index to acess each element.

print(an_array[0],an_array[1], an_array[2]) 

3 33 333


In [9]:
an_array[0] = 888  # change value of 0 index value, array is mutuble

print(an_array)

[888  33 333]


# 2D Array

In [32]:
# a rank 2nd array is one with two dimension.
# the format below of [row],[row], [2] dimesional arrays are greate for represting matrics which are are often useful in data science.

another = np.array([[11,12,13],[21,22,23]])

print(another) # print the array

print("the shape is 2 rows, 3 columns :",another.shape)  # row * columns

print("Acessing elements [0,0],[0,1] and [1,0] of the array :", another[0,0], ", ", another[0,1], ", ", another[0,2])

[[11 12 13]
 [21 22 23]]
the shape is 2 rows, 3 columns : (2, 3)
Acessing elements [0,0],[0,1] and [1,0] of the array : 11 ,  12 ,  13


In [10]:
# create a 2 X 2 array of zeros matrix

ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [11]:
# create a 2 X 2 array filled with 9.0
# 3 row, 3 column give 9 value
ex2 = np.full((3,3), 9.)
print(ex2)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [12]:
# idenity matrix 
# create a 2 X 2 matrix with the diagonal 1 and other 0

ex3 = np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [13]:
# create an array of ones

ex4 = np.ones((2,1))
print(ex4)

[[1.]
 [1.]]


In [14]:
print()

print(ex4[0,0]) # position 


1.0


In [16]:
# create an array of random float random no between 0 and 1 

ex5 = np.random.random((2,2))

print(ex5)

[[0.00271775 0.46437758]
 [0.87821178 0.21767238]]


# Slice Indexing

In [1]:
import numpy as np

In [2]:
an_array = np.array([ [11,12,13,14], [21,22,23,24], [31,32,33,34] ])

print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [3]:
# use array slicing to get subarray consisitng of the first 2 rows x 2 columns

a_slice = an_array[0:2, 1:3] #[row, column] 0:2 row, 1:3 column value
print(a_slice)

[[12 13]
 [22 23]]


In [4]:
# when you change, you actually change the underlying array.

print("Before :", an_array[0,1]) #inspect the elemet of 0 and 1.

a_slice[0, 0] = 1000  # a_slice[0,0] is the same piece of data as an_array[0,1]

print("After :", an_array[0,1])

Before : 12
After : 1000


In [5]:
a_slice1 = an_array[1, :] #[row, column] 0:2 -> first 2 rows, 1:3-> first two data (single diamension)
# 1 no column display with all value we not here column value thats why all value disaply
print(a_slice1)

[21 22 23 24]


In [6]:
print(a_slice1.shape)   #shape -> row, column (single diamension)

(4,)


In [7]:
a_slice2 = an_array[1:2,0:]  #1:2 -> 1 coloumn, 0: all value (multi dimension)
print(a_slice2.shape)

(1, 4)


In [8]:
#create a ranke 2 array of shae(3,4), 3 row,4 column.
an_array = np.array([ [11,12,13,14], [21, 22, 23, 24], [31, 32, 33, 34] ])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [9]:
#using both integer indexing & slicing generates an array of lower rank 

row_rank1 = an_array[1, :]

print(row_rank1, row_rank1.shape) # only a single []

[21 22 23 24] (4,)


In [10]:
# slicing alone: generates an array of the same rank as the an_array 

row_rank2 = an_array[1:2, :] # rank 2 viewt

print(row_rank2, row_rank2.shape) # 2nd column acess, 1 columns 4 value as shape row and column

[[21 22 23 24]] (1, 4)


In [11]:
# we can do the same thing for columns of an array (not understand)

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape) # rank1, here row with 3 value consider horizonal
print()
print(col_rank2, col_rank2.shape) # rank2, here columns with 3 value consider verticle



[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [12]:
# create a new array
an_array = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43] ])

print("Origional Array :")

print(an_array)

Origional Array :
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [13]:
# Create an array of indices / index

col_indices = np.array([0, 1, 2, 0]) # which columns you want to print 
print("\n Col Indices Picked :", col_indices)

row_indices = np.arange(4) # arrange consider index as 0,1,2, 3
print("\n Row Indices Picked :", row_indices)


 Col Indices Picked : [0 1 2 0]

 Row Indices Picked : [0 1 2 3]


In [14]:
#Zip function
# examine the pair of row_indices and col_indices.
# these are the element wil change next.

for i, j in zip(row_indices, col_indices):
    print(i, ", ", j)
    
"""
    for i in row_indices
        for j in col_indices
"""

0 ,  0
1 ,  1
2 ,  2
3 ,  0


'\n    for i in row_indices\n        for j in col_indices\n'

In [15]:
# select one element from each one
# an_array = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43] ])

print("Values in the array at those indices : ", an_array[row_indices, col_indices])
 
#an_array[0,0], an_array[1,1], an_array[2,2], an_array[3,0] = an_array[row_indices, col_indices]

""" 
[[11 12 13]
  [21 22 23]
  [31 32 33]
  [41 42 43]] 
""" 

Values in the array at those indices :  [11 22 33 41]


' \n[[11 12 13]\n  [21 22 23]\n  [31 32 33]\n  [41 42 43]] \n'

In [16]:
# change one element from each row using the indices element.

# an_array = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43] ])
# an_array[0,0], an_array[1,1], an_array[2,2], an_array[3,0]
 
an_array[row_indices, col_indices] += 1000

print("\n Changes Array: ")
print(an_array)


 Changes Array: 
[[1011   12   13]
 [  21 1022   23]
 [  31   32 1033]
 [1041   42   43]]


In [17]:
# create a 3 x 2 array
an_array = np.array([ [11,12], [21,22], [31,32] ])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [18]:
# create a filter which will be boolena value for whether eeach elemement meet this condition
filter = (an_array > 15)
filter


array([[False, False],
       [ True,  True],
       [ True,  True]])

### Usefilter in array

#### that filter is a same size ndarray as an_array which is filled with true for each elemennt whose coresponding element in an_aaray which is greter then 15 and false for those elements whoise value is less than 15

In [19]:
# we can now select just those element which meet that criteria

print(an_array[filter])

[21 22 31 32]


In [20]:
print(an_array > 15)

[[False False]
 [ True  True]
 [ True  True]]


In [21]:
print(an_array[filter] > 15)

[ True  True  True  True]


In [22]:
an_array[an_array > 15]

array([21, 22, 31, 32])

#### what is particularly is that we can actually change elements in the array applying asimilar logical value.
#### lets the even value

In [24]:
an_array[an_array % 2 == 0] +=100 #a+=100 is same as a= a+100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


# Datatype

In [25]:
ex1 = np.array([11,12]) # python assign the datatype
print(ex1.dtype)

int32


In [26]:
ex2 = np.array([11.0,12.0]) # python assign the datatype
print(ex2.dtype)

float64


In [27]:
ex3 = np.array([11,21], dtype=np.int64) # YOU CAN ALSO TELL PYTHON DATATYPE
print(ex3.dtype)

int64


In [28]:
# you can use this to force float into integer (using flooer function)
# give float value convert into integer

ex4 = np.array([11.1,12.7], dtype=np.int64)

print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [30]:
# YOU CAN USE THIS TO FORCE INTEGER INTO FLOAT IF YOU ANTICIPTATE
# the values may change to float later
# give integer value convert into float

ex5 = np.array([11, 21], dtype=np.float64)

print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


# Arthimatic Operator

In [3]:
import numpy as np

In [4]:
x = np.array([ [111,112], [121,122] ], dtype=np.int)
y = np.array([ [211.1, 212.1], [221.1, 222.1] ], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [5]:
# add

# x = np.array([[111,112], [121,122]], dtype=np.int)
# y = np.array([[211.1, 212.1], [221.1, 222.1]], dtype=np.float64)

print(x+y) # the plus sign

print()

print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [6]:
# subsctract

# x = np.array([[111,112], [121,122]], dtype=np.int)
# y = np.array([[211.1, 212.1], [221.1, 222.1]], dtype=np.float64)

print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [7]:
# multiplication

# x = np.array([[111,112], [121,122]], dtype=np.int)
# y = np.array([[211.1, 212.1], [221.1, 222.1]], dtype=np.float64)

print(x*y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [8]:
# divide

# x = np.array([[111,112], [121,122]], dtype=np.int)
# y = np.array([[211.1, 212.1], [221.1, 222.1]], dtype=np.float64)

print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [9]:
# square root
# x = np.array([[111,112], [121,122]], dtype=np.int)

print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [10]:
# exponent (e ** x)
# x = np.array([[111,112], [121,122]], dtype=np.int)

print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [11]:
# setup a random 2 x 5 matrix
arr = 10 * np.random.randn(2,5) # random.random or random.randn or random.randint
print(arr)

[[ -3.99376357   7.75923516   3.11438873  10.10138034   8.63411625]
 [ -0.70429602 -10.71074377  -1.84638533   0.13184596   3.30692013]]


In [12]:
# compute the mean for all elemets
print(arr.mean()) # total matrix mean

1.5792697881889648


In [13]:
# compute the mean by row by -> 5 row
print(arr.mean(axis=1)) 

[ 5.12307138 -1.96453181]


In [14]:
# compute the mean by column -> 5 column
print(arr.mean(axis=0))

[-2.3490298  -1.4757543   0.6340017   5.11661315  5.97051819]


In [15]:
# compute the mean by column
print(arr.mean(axis=0))

[-2.3490298  -1.4757543   0.6340017   5.11661315  5.97051819]


In [16]:
# sum all the elements
print(arr.sum())

15.792697881889648


In [17]:
# compute the median
print(np.median(arr, axis=1)) # by row 1st and 2nd also

[ 7.75923516 -0.70429602]


### Sorted And Unsorted (imp for interview)

In [18]:
# create a 10 element array of random (# important)

unsorted = np.random.randn(10)
print(unsorted)

[ 0.16723027 -0.68761158 -0.39551205 -0.68163265 -0.85147094  0.87689656
  0.9301791   0.0671494  -0.07914835  0.80883363]


In [19]:
# create copy and sort (# important)

sorted = np.array(unsorted)
sorted.sort() # it will arrange values in ascending order i.e sorting

print(sorted)
print()
print(unsorted)

[-0.85147094 -0.68761158 -0.68163265 -0.39551205 -0.07914835  0.0671494
  0.16723027  0.80883363  0.87689656  0.9301791 ]

[ 0.16723027 -0.68761158 -0.39551205 -0.68163265 -0.85147094  0.87689656
  0.9301791   0.0671494  -0.07914835  0.80883363]


In [20]:
#inplace sorting (# important)
unsorted.sort()
print(unsorted)

[-0.85147094 -0.68761158 -0.68163265 -0.39551205 -0.07914835  0.0671494
  0.16723027  0.80883363  0.87689656  0.9301791 ]


### finding Unique Elements (Imp for interview)

In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 1, 4, 2, 1, 4, 2])
print(np.unique(array)) # it will return unique values

[1 2 4]


In [3]:
#5-10-2021

In [4]:
s1 = np.array(["desk", "chair", "bulb"])
s2 = np.array(["lamp", "bulb", "chair"])

print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [5]:
print(np.intersect1d(s1,s2)) # intersect is acess commomn value from both array

# common value from s1 and s2

['bulb' 'chair']


In [6]:
print(np.union1d(s1,s2))
# union is acess common and unique value only not rperated valuen value from both array
# common 

['bulb' 'chair' 'desk' 'lamp']


In [7]:
print(np.setdiff1d(s1,s2)) # elemets in s1 that are not in s2

['desk']


In [8]:
print(np.in1d(s1,s2)) # which elemet of s1 is also in s2

[False  True  True]


### Broadcasting

In [1]:
import numpy as np

In [2]:
start = np.zeros((4,3)) # 4 row, 3 column
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# create a rank_1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [4]:
# add to each rows of 'start' using broadcasting
y = start + add_rows  
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [5]:
# create an ndarray which is 4 x 1 broadcast acrosss columns

add_cols = np.array([[0, 1, 2, 3]]) # print add column 
add_cols = add_cols.T #transpose: coverts rows into columns and vice versa
  
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [6]:
# add to each column of "start" using broadcasting

y = start + add_cols

print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [7]:
# this will just broadcast in both dimesions

add_scalar = np.array([1])

print(start + add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# example from the sildes:

In [9]:
# create our 3 x 4 matrix
arrA = np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12] ]) 
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
# create our 1 x 4  array

arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [11]:
# add the two together using broadcast
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


In [12]:
from numpy import arange
from timeit import Timer

size = 1000000
timeits = 100

In [13]:
# create the ndarray with values 0,1,2...., size-1
nd_array = arange(size)
print(nd_array)

[     0      1      2 ... 999997 999998 999999]


In [14]:
# timer expects the operation as parameter
# here we apss nd_array.sum()

timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000712 seconds


In [15]:
# creator the list with values 0,1,2...,size-1
a_list=list(range(size)) #range(end) 1000000
print(type(a_list)) 

<class 'list'>


In [46]:
# timer expects the operation as a paramter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list: %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list: 0.031877 seconds


In [18]:
import numpy as np

In [19]:
x = np.array([23.23, 24.24]) #save the values in x to an_array

In [20]:
np.save("an_array", x)

In [21]:
np.load("an_array.npy")

array([23.23, 24.24])

### Text Format:

In [26]:
np.savetxt("array.txt", X=x, delimiter=",") # savetxt function will store your file in text format.
np.loadtxt("array.txt", delimiter=",") # delimiter and sep are same which is seprated by comma.

array([23.23, 24.24])

### Adictional common ndarray opeartion.

### Dot Product On Matrices and Inner Product On Vector

In [29]:
x2d=np.array([[1,1],[1,1]])
y2d=np.array([[2,2],[2,2]]) 

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

""" 
for 1st element: 1st row1 1st element1 * 1st column2 1st element2
+  1st row1 2nd element1 * 1st column2 2nd element2
"""

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [39]:
# determine the inner product of two vector
a1d=np.array([9, 9])
b1d=np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))

# matrix : 9*10 + 9*10 = 180

# scalar: has magnitude vector has direction  
# vector: physical quantity having magnitude and direction
# matrix: has row or column multidimension

180

180


In [40]:
# dot produce on an array and vector
print(x2d.dot(a1d))
print()
print(np.dot(x2d,a1d))

#[(9,9)],([[1,1],[1,1]])

#[1*9 + 1*9, 1*9 + 1*9]=[18, 18] 

[18 18]

[18 18]


### Add value sum

In [41]:
# element sum in the array

ex1 = np.array([ [11,12], [21,22]])

print(np.sum(ex1)) # add all value 

66


In [42]:
print(np.sum(ex1,axis=0)) # column wise sum

[32 34]


In [43]:
print(np.sum(ex1,axis=1)) # row wise sum

[23 43]


In [44]:
# radom array 
x = np.random.randn(8)
x

array([-0.59582927,  0.13601431,  0.05675372, -2.35273997,  0.61904735,
       -0.15898756,  2.50713243, -1.14511389])

In [7]:
# another radom array 
y = np.random.randn(8)
y

array([-0.86432907,  0.45109174,  1.13280292,  0.09380576, -0.7968716 ,
       -1.02900758,  1.04963931,  0.44428128])

In [ ]:
# return element wise maximum between two array.

import numpy as np

x = np.random.randn(8)
y = np.random.randn(8)

print(x)
print(y)

np.maximum(x,y)

# maximum: it will return elementwise maximum value

In [2]:
# Reshape Array

In [4]:
# grab values from 0 troght 10 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
# reshape to be a 4 x 5 matrix

arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
# reshape to be a 5 x 4 matrix

arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Transpose

In [ ]:
import numpy as np

In [11]:
# transponse :  convert rows into column
ex1 = np.array([ [11,12], [21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

# Indexing using where():

In [19]:
import numpy as np

x_1 = np.array([1, 2, 3, 4, 5]) # Consider Value True

y_1 = np.array([11, 22, 33, 44, 55]) # Consider Value False

#where we have true in filter it will print x_1 value and for false y_1 value
# this is the working of where function

filter = np.array([True, False, True, False, True])

In [20]:
out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [29]:
mat = np.random.rand(5,5)
mat

array([[0.16225   , 0.40205945, 0.61046742, 0.86312025, 0.02473577],
       [0.44917974, 0.52208867, 0.54272625, 0.48026157, 0.06870673],
       [0.28447875, 0.43454966, 0.88771644, 0.07824582, 0.54167079],
       [0.65580563, 0.71806206, 0.2701961 , 0.33274644, 0.82854437],
       [0.45213084, 0.4933687 , 0.79433384, 0.47442395, 0.1576107 ]])

In [32]:
np.where(mat > 0.5, 1000, -1)


#if mat > 0.5:
#    replace(1000)
#else:
#    replace(-1)


array([[  -1,   -1, 1000, 1000,   -1],
       [  -1, 1000, 1000,   -1,   -1],
       [  -1,   -1, 1000,   -1, 1000],
       [1000, 1000,   -1,   -1, 1000],
       [  -1,   -1, 1000,   -1,   -1]])

# "Any" or "All" condition:

In [33]:
arr_bool = np.array([True, False, True, True, False])

In [34]:
arr_bool.any() # it is any value True

True

In [35]:
arr_bool.all() # it is all value True

False

In [37]:
import numpy as np

y = np.random.normal(size=(1,5))
print(y)

[[ 0.03087775 -0.52116089  0.61463108  0.94331501 -1.28846164]]


In [38]:
z = np.random.randint(low=2,high=50, size=4) #int integer value
print(z) # low for lower limit and high for higher limit

[47  2 23 39]


In [39]:
np.random.permutation(z) # return a new ordering of elemets in z

array([23,  2, 47, 39])

In [40]:
np.random.uniform(size=4) # uniform distribution

array([0.49338372, 0.02630436, 0.10829818, 0.26461776])

In [41]:
np.random.normal(size=4) # normal distribution

array([-0.65253681,  1.2423902 ,  1.61733502,  0.39523614])

# Data Merge

In [51]:
k = np.random.randint(low=2,high=50,size=(2,2))
print(k)

print()

m = np.random.randint(low=2,high=50,size=(2,2))
print(m)

[[12 43]
 [18 35]]

[[34 48]
 [13 14]]


In [52]:
np.vstack((k,m)) # vertically join

array([[12, 43],
       [18, 35],
       [34, 48],
       [13, 14]])

In [59]:
np.hstack((k,m)) # horizontally join

array([[12, 43, 34, 48],
       [18, 35, 13, 14]])

In [60]:
np.concatenate([k,m],axis=0) # 0 consider row

array([[12, 43],
       [18, 35],
       [34, 48],
       [13, 14]])

In [66]:
np.concatenate([k,m.T],axis=1) # T for transpose,

array([[12, 43, 34, 13],
       [18, 35, 48, 14]])